export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT__DETAILS_REQUEST = 'PRODUCT__DETAILS_REQUEST';
export const PRODUCT__DETAILS_SUCCESS = 'PRODUCT__DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_LIST_DETAILS_FAIL';

